### ISSUE TITLE
Collada loading possibilities

### ISSUE THREAD

**Issue by sergiota** [buildar/awe.js#11]
Hello!
Is there any possibility to load a Collada 3D model in the current build ?
If there is not, please, give me some hints and advices where and how I can integrate the Collada loader.
Thanks in advance!

**Comment by robman** [comment]
You can use one of the other loaders supported by THREE if you extend awe.js (see how the THREE.OBJLoader is used already in awe.js).

BTW: We'll be adding support for up to 40 different 3D formats including glTF in an upcoming release. But I can't give you an ETA for that right now.

**Comment by sergiota** [comment]
Thank you, Rob!
And do you have any documentation for awe.js?
Everything I could find is the presentation at buildAR.com and a few articles over the net.

**Comment by robman** [comment]
We're working on this at the moment as part of a new API update too.
Unfortunately I can't give you any timing on this being published.
