### ISSUE TITLE
Is it possible to load a model using Three.JSONLoader?

### ISSUE THREAD

**Issue by micronaut** [buildar/awe.js#13]
I am trying to load a model into awe using Three.JSONLoader.  If I use console.log(awe.projections.list()); I can see a list of objects and the model listed as THREE.Mesh but it is not rendering.
Thanks, 
Eric

**Comment by MichaelHazani** [comment]
Hey Eric - take a look at https://github.com/buildar/awe.js/issues/11 (in short, yes:)

**Comment by micronaut** [comment]
Thanks!
