### ISSUE TITLE
Use with cordova?

### ISSUE THREAD

**Issue by graydetroit** [buildar/awe.js#14]
Question: Seeing as how cordova-based hybrid and cross-platform applications expose system functionality but still utilize web technologies - could this library be tuned to work with iOS as well as Android based platforms via a cordova setup? There are even cordova-based plugins such as [this one](https://github.com/eface2face/cordova-plugin-iosrtc) that expose the full WebRTC JS APIs for iOS. I'm wondering if Awe.js could be made to work in this sort of scenario - and I would love helping in anyway I can to provide an extension for this library if necessary. Thanks!

**Comment by grabcode** [comment]
@jamesgrayillustration have you tried by yourself mate? I'm thinking to do that in the following fortnight.

**Comment by hamdi-charef** [comment]
I tried Awe.js with cordova,nothing appear on the screen of the application although the code work's fine on the browser.

**Comment by stephane-lb** [comment]
@hamdi-charef I am interesting by the challenge, could you share some code please ?

I am thinking to use a library like  http://www.ezartech.com to plug get the video, hope I will be able to get something working then ;-)

**Comment by ezalorsara** [comment]
I already tried it in cordova and ionic, it works. 
you just need to install cordova crosswalk plugin.

**Comment by robman** [comment]
Hi @graydetroit, @grabcode, @hamdi-charef, @stephane-lb and @ezalorsara apologies for the lack of replies while we were in stealth mode. You can checkout our new repos at https://github.com/awe-media/awe.js which includes some new docs in the wiki.

This should work fine in cordova but please raise an issue in the new repos if you find anything that doesn't.

**Comment by sebi-b** [comment]
hello!
@ezalorsara, I also tried that but can't get the video input... Are there any news regarding that?
Thanks!

**Comment by dimpapadop** [comment]
I cannot seem to make it show video input in cordova app either.
Could the issue reopen to help each other?
maybe a sample geo-ar cordova project

i installed webwalk, i changed android manifest to allow camera, but no luck yet

**Comment by JuanSeBestia** [comment]
on Android and Borwser work good, but on iOS not
