### ISSUE TITLE
Question: add custom Marker, Documentation

### ISSUE THREAD

**Issue by TheCell** [buildar/awe.js#15]
Hey there got the marker 64 working on my demo and can change the displayed object etc. but I struggle to add a custom marker. Can somebody hint me in the right direction? I don't get where the marker 64 is loaded into the detector at all.
Is there a documentation vor awe.js? Or even the underlying JSARToolkit?

**Comment by BennettWerner** [comment]
Found the markers, they are in the JSARToolKit-master/demos/markers 

https://github.com/kig/JSARToolKit

I'm also looking to add a custom marker

**Comment by playwolf719** [comment]
@TheCell @BennettWerner Do you guys have any ideas about the custom marker

**Comment by robman** [comment]
Hi @playwolf719 / @TheCell / @BennettWerner  - apologies for the lack of support. We've moved over to a new repos now (https://github.com/awe-media/awe.js) and will be closing out any issues left here soon.

The ARToolkit people have a tutorial on creating custom markers here https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_training

Hope that helps.

BTW: See the new examples/marker_ar - it's even easier to bind pois to marker id's now.

I'll close this now but shout if you have any other questions.

**Comment by playwolf719** [comment]
@robman Thx, guys
