### ISSUE TITLE
Question: Geo location base object.

### ISSUE THREAD

**Issue by 5y** [buildar/awe.js#17]
Hi,
How to use real Geo location detail in awe.js ?
For example using awe.js application at predefine place looks like a part of the city.

Bests,
Reza

**Comment by mikeres0** [comment]
+1, would be a great feature to implement if it isn't already

**Comment by 5y** [comment]
Hi @mikeres0,
I tried to Develop Geo location for Awe.js  and ASAP I put my code in github.
Bests,
Reza

**Comment by Caliqo** [comment]
Hi 5y. Have you had any success with the geo location? I am hoping to use fixed coordinates too, but I am pretty lost so I am hoping there is someone out there who has got it to work so I can ask for advice.

**Comment by robman** [comment]
Hi @5y, @mikeres0 and @Caliqo apologies for the lack of replies while we were in stealth mode. You can checkout our updated repos at https://github.com/awe-media/awe.js - and if you have any questions about geolocation please raise an issue there. If you could be more specific about how you want to use geolocation that would help us answer your question in more detail.

**Comment by 5y** [comment]
@Caliqo @mikeres0 Sorry guys I have no idea why I missed notifications of this thread .
In fact, the idea is so simple, I used regular google geolocation for find the coordinate then on the certain coordinate I called the Awe.js sense  , Asap I will upload my script.

@robman Your platform needed some improvement such as Good Wiki page and tutorial and I can recognize a good potential for Awe.js as solid AR web platform.

**Comment by robman** [comment]
Hey @5y - checkout the new repos with the start of our new wiki docs https://github.com/awe-media/awe.js/wiki

@5y, @Caliqo & @mikeres0 we'll also be releasing a whole set of new geo functionality after the xmas break so stay tuned for that (over at the new repos).

And all other suggestions or issues welcome there too.
