### ISSUE TITLE
Loading, progress bar 

### ISSUE THREAD

**Issue by elektrikmoonkey** [buildar/awe.js#19]
Hi there, does anyone know how to create a loading bar on geo location example?
Going around in circles and still at point 0.

**Comment by elektrikmoonkey** [comment]
For those ho seek the loading bar.
A tricky dirty way is this:
Html div 
`<progress id='p' class='determinate' value='0' max='100'></progress>`

Then you need to find awe-standard-dependencies.js line 224 - 230

`THREE.XHRLoader.prototype = { 
    constructor: THREE.XHRLoader, load: function (a, b, c, d) {
        var e = this, f = new XMLHttpRequest;
//insert pbar here
        var pBar = document.getElementById('p');
        progress.style.display = "block";

        void 0 !== b && f.addEventListener("load", function (c) {
            b(c.target.responseText); 
            e.manager.itemEnd(a);           
           // console.log(b);
        }, !1);
//and this loading function here
        void 0 !== b && f.addEventListener("progress", function (a) {
           // b(a);
            //console.log(a);
            if (a.lengthComputable) {
                var total = a.total;

                var percentComplete = a.loaded / total * 100;
                var percent = Math.round(percentComplete, 2);
                //console.log(Math.round(percentComplete, 2) + '% downloaded');              

                pBar.value = percent;
                val.innerHTML = percent + '%';
              
                // progress.style.display = "none";/*
                if (percent >= 100) {
                   progress.style.display = "none";     
                };
            }
        }, !1);
   `
Hope it helps, maybe you can move this code to another place

**Comment by robman** [comment]
Hi @elektrikmoonkey - apologies for the lack of replies while we were in stealth mode. Checkout the code in our new repos at https://github.com/awe-media/awe.js - this now includes support for `progress_callback` handling. The wiki now includes some docs and we'll add a page on progress handling soon.
