### ISSUE TITLE
No camera view on android with cordova. Browser doesn't support VR

### ISSUE THREAD

**Issue by mladenp** [buildar/awe.js#23]
I tried to use awe geolocation example and managed to setup everything correctly and see 3d models but no camera view.
I am using cordova with ionic on Android. I tried adding crosswalk but still nothing.
It gives me warning: "Your browser doesn't support VR"
i am using Android 6, its webview should support camera view as far as i know.

**Comment by robman** [comment]
Closing - see https://github.com/awe-media/awe.js/issues/4
