### ISSUE TITLE
Can we have access to rear camera on phones?

### ISSUE THREAD

**Issue by bbhide** [buildar/awe.js#24]
This library works great. But only challenge I'm facing right now is the chrome web browser accesses front camera. while I'm developing a web app which should be able to use the rear camera as that would be more useful for Augmented reality operations.

I've tried stackoverflow http://stackoverflow.com/questions/18625007/enable-rear-camera-with-html5 but "getSources" has been now deprecated which is kind of a bummer.

Can anyone help me with this?

**Comment by robman** [comment]
See the new generation awe.js repos which includes a fix for this at https://github.com/awe-media/awe.js
