### ISSUE TITLE
Awe.js with geolocation

### ISSUE THREAD

**Issue by silviuvert** [buildar/awe.js#3]
How do you display some Points of Interest (for which you have latitude, longitude and, optionally, altitude) using awe.js?

**Comment by Caliqo** [comment]
Hello! I am trying to make a geo-ar scenario using the geo-ar demo here on Github as a template. I have tried this code as many different way as I can think of, but I can not get it to work. The demo remains with the POIs being relative to the user. It doesn't seem to recognize the switch to fixed positions. Is there an example out there anywhere I can refer to? Thank you!

**Comment by sebi-b** [comment]
Hey there! I'm also trying to figure out, how to display different locations using the longitude and latitude attribute. But as Caliqo wrote its not working.... Are there any other solutions? THanks!

**Comment by syc-pad** [comment]
+1

**Comment by robman** [comment]
Hi @syc-pad this repos is deprecated so please raise any issues over on the new one (NOTE: This is covered in the README at the top of this repos).

There's a range of useful tips from the @awe-media team plus other users on different projection models for geolocation in [issue #18](https://github.com/awe-media/awe.js/issues/18).

Plus I'd recommend checking out the https://awe.media platform that provides a simple drag'n'drop interface for creating Locative AR and 360°/VR content.

**Comment by syc-pad** [comment]
Thank you @robman ! 👍
