### ISSUE TITLE
awe.js banned by adblock

### ISSUE THREAD

**Issue by pyalot** [buildar/awe.js#4]
EasyList, used by adblock, adblock plus, ublock any virtually every other adblocking service, has banned the filename "/awe.js".

https://easylist-downloads.adblockplus.org/easylist.txt

**Comment by robman** [comment]
Doh - apologies for leaving this open so long 8/

This was a good point that was raised by a few people and lead to use renaming the base files to awe-loader.js and awe-standard.js. 

Ironically awe.js now seems to have been removed from this list and a few others (see awe2.js now). But we'll leave our files with the new names.

Closing now but please re-open if any other blocking issues like this are found.
