### ISSUE TITLE
Video support ?

### ISSUE THREAD

**Issue by DigitalSismo** [buildar/awe.js#5]
Hi,
Can you replace the picture (awe_by_buildAR.png) used as "texture" by a video ? If so, how do you do that ?

Thank you for your help.

**Comment by Ouaps** [comment]
Hello, 
I'm trying to replace the picture by a video in .webm but it doesn't work... Can you explain me how did you do this ? I followed the instructions done in the awe.js tutorial but, it's doesn't work.
When i do this and when i run the program in the last Firefox"s version it doesn't work and debugguers say me : "Error: WebGL: The canvas used as source for texImage2D here is tainted (write-only). It is forbidden to load a WebGL texture from a tainted canvas. A Canvas becomes tainted for example when a cross-domain image is drawn on it. See https://developer.mozilla.org/en/WebGL/Cross-Domain_Textures".

I try to understand but i'm begineer and if you can explain me why it doesn't word for videos, it would be wonderfull !
It was easy to run the video in 3d form with three, the program run but not here...
Thanks !

**Comment by robman** [comment]
Hi @DigitalSismo and @Ouaps apologies for missing this issue.

This will work with Firefox but the normal CORS rules apply so you should load the video from the same host to make this easier (or adjust your CORS config).

The problem with Chrome and Opera is that they require a user touch event to start the playing of the media. This is a policy decision and you can see the background and a full discussion here https://code.google.com/p/chromium/issues/detail?id=178297

Hopefully this will change at some point in the future - but until then you can use a "start" button to work around this.

**Comment by DigitalSismo** [comment]
@robman Thank you for your reply :)
