### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mutsche** [buildar/awe.js#6]
Hi,

can you please add license information?
As you wrote a thanks to ARToolkit I suspect that you used the js-port of it, tying the lib to GPL V3, but that would be deadly for adoption :-(

best regards
Mario

**Comment by robman** [comment]
Hi @mutsche ,

all awe.js libs are clearly licensed under the MIT license - and all files should clearly include the relevant licenses. Please let us know if you find any that don't.

There is a standalone awe.marker_ar.js plugin that makes it easy to utilise the jsartoolkit library.
https://github.com/buildar/awe.js/tree/master/examples/marker_ar
https://github.com/buildar/awe.js/blob/master/examples/marker_ar/awe.marker_ar.js
https://github.com/buildar/awe.js/blob/master/examples/marker_ar/awe-jsartoolkit-dependencies.js
This also includes it's relevant licenses and credit back to Mark Billinghurst, Hirokazu Kato, the HITLab, Ryo Iizuka and Ilmari Heikkinen.
